# Generated using https://godot-build-options-generator.github.io

extra_suffix = "PurpleRiver_v0.6.2"
disable_3d = "yes"
optimize = "size"
deprecated = "no"
vulkan = "no"
module_camera_enabled = "no"
module_enet_enabled = "no"
module_freetype_enabled = "no"
module_gltf_enabled = "no"
module_hdr_enabled = "no"
module_ktx_enabled = "no"
module_meshoptimizer_enabled = "no"
module_mobile_vr_enabled = "no"
module_msdfgen_enabled = "no"
module_multiplayer_enabled = "no"
module_navigation_enabled = "no"
module_openxr_enabled = "no"
module_raycast_enabled = "no"
module_squish_enabled = "no"
module_upnp_enabled = "no"
module_webxr_enabled = "no"
module_zip_enabled = "no"
test_test_test = "yes"